### ISSUE TITLE
Polish the game/UI

### ISSUE THREAD

**Issue by Omar-Alkesh** [tevisdoe/Archeo-Puzzle-SFWRENG-3GB3#3]
Details for this can be added by @tevisdoe. Or please let me know what details I can add.

- [ ] Update the book tabs to match the book style
  - [ ] Remove the colour tint when switching tabs
- [ ] Style the solve menu to match the rest of the game
  - [ ] Improve the layout of the input
  - [ ] Improve the styling on the dialog
  - [ ] Change the colours/use pictures

I will try to add anything else once I recall it.

**Comment by tevisdoe** [comment]
I have added some minor changes all around that should make the game feel a little bit better. I also updated the databank image. I'm not sure if it looks better or not? It's a real book now, but I really like it.
