### ISSUE TITLE
Improve the solve dialog

### ISSUE THREAD

**Issue by Omar-Alkesh** [tevisdoe/Archeo-Puzzle-SFWRENG-3GB3#4]
* [x] Fix and improve the date input
  * [x] Use a dropdown menu for the AD/BC
  * [x] Use numbers only input for the date
  * [x] Validate negative and positive numbers
* [ ] Add a more detailed location choice
  * Maybe use a map?
  * Add more options for the region
  * Add subregion choices?
* [x] See what else can be fixed

**Comment by OZoneGuy** [comment]
Decided against adding a sub-region dropdown. Best to use a map, but need to add pictures to the book.
