### ISSUE TITLE
Add a new puzzle

### ISSUE THREAD

**Issue by Omar-Alkesh** [tevisdoe/Archeo-Puzzle-SFWRENG-3GB3#8]
The sword:
* Have three main sections
  * Blade
  * Guard
  * Handle
* Each section returns a different material composition
* [x] Add a new section to the book about swords
* [x] Choose the period and region of the sword
  * [x] Decide on the material composition for each section
  * [x] Decide on the shape, or just use whatever model we get :/
* [x] Get the sword model
* [x] See if there is anything else needed for the puzzle
  * [ ] Possibly a Carbon dater, to determine the age of the leather on the handle.

**Comment by tevisdoe** [comment]
We might want to make more than one puzzle, FYI. That's what we have scoped to the design document, and I think we should follow through with it. It doesn't have to be for the demo, but we _do_ need around 10 minutes of gameplay, according to the rubric for milestone 4.

**Comment by OZoneGuy** [comment]
For the demo, we should try to stick to one. Then the final demo, we should definitely add more. If we have time to add them all now, then we should. But I don't think we have the time to do so.

**Comment by tevisdoe** [comment]
> For the demo, we should try to stick to one. Then the final demo, we should definitely add more. If we have time to add them all now, then we should. But I don't think we have the time to do so.

I defer to your judgement. Was merely a suggestion.
