### ISSUE TITLE
Add a level menu

### ISSUE THREAD

**Issue by Omar-Alkesh** [tevisdoe/Archeo-Puzzle-SFWRENG-3GB3#9]
A screen to choose which level/puzzle to attempt.

Ask @melissa-kun-li to review, make sure it fits the theme.

**Comment by tevisdoe** [comment]
Level menu has been added to the main menu, based on the images provided by melissa in our initial design doc. I will ask her to look at the project later.

**Comment by OZoneGuy** [comment]
Looks good to me. But I am concerned about expanding for more than two puzzles. Do we see this as an issue?

**Comment by tevisdoe** [comment]
Since we only plan to have a maximum of 3 puzzles, this is fine. Adding a new level is easy enough as well. Obviously this wouldn't be the approach if we wanted say, 10 puzzles, but I think that for now it's fine.
